### ISSUE TITLE
New idea for /top

### ISSUE THREAD

**Issue by BolverBlitz** [TheWildBear/telegramMsgCounterbot#2]
/top also could show how many messages the user wrote since the last /top command
Or it shows an avrage of the last 24 Hours / 1Week idk.

**Comment by BolverBlitz** [comment]
I would also appreciate tendency

**Comment by TheWildBear** [comment]
Great idea! I'll work on that as soon as possible! @BolverBlitz 
I'll have to see what's the best way to make this behavior happen!
